services:
  n8n:
    image: n8nio/n8n:latest # 最新版のn8nイメージを指定
    container_name: n8n_local # コンテナ名を指定 (任意)
    restart: unless-stopped # コンテナが停止した場合、手動で停止しない限り再起動
    ports:
      - "5678:5678" # ホストOSの5678番ポートをコンテナの5678番ポートに接続
    environment:
      # 重要: ワークフローの認証情報などを暗号化するためのキー
      # 下記のコマンドで生成したランダムな文字列を設定してください
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      # タイムゾーンを日本時間に設定
      - GENERIC_TIMEZONE=${TZ:-Asia/Tokyo}
      # その他の設定が必要な場合はここに追加
      # 例: - N8N_EMAIL_MODE=smtp
      #     - N8N_SMTP_HOST=your_smtp_host
      #     ...
    volumes:
      # n8nの設定データやワークフローデータを永続化するためのボリューム
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    # 外部ボリュームを使用する場合などは、ここに設定を追加